# Reading Files with Pandas

In this section we will use Pandas to explore tabular datasets (mainly in CSV form)

## Input Data

Our input data contains various data files from the New York Times about Covid-19 spread across the entire world. You can download the files from their GitHub repository https://github.com/nytimes/covid-19-data

As a starter we will look into the file facilities.csv which contain the details of Covid19 spread in correctional facilities. During the pandemic outbreaks were common in confined facilities such as prisons, carehomes, and nursing homes.

## Reading a CSV File In Pandas

For reading a CSV file we utilize the read_csv() function from Pandas. The read_csv function expects a file-path and it also has many optional parameters to modify the way in which the file is read.

In [1]:
import pandas as pd

If you want to know the details about the function read_csv you can do the following

In [2]:
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    sep=<no_default>,
    delimiter=None,
    header='infer',
    names=<no_default>,
    index_col=None,
    usecols=None,
    squeeze=None,
    prefix=<no_default>,
    mangle_dupe_cols=True,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters=None,
    true_values=None,
    false_values=None,
    skipinitialspace=False,
    skiprows=None,
    skipfooter=0,
    nrows=None,
    na_values=None,
    keep_default_na=True,
    na_filter=True,
    verbose=False,
    skip_blank_lines=True,
    parse_dates=None,
    infer_datetime_format=False,
    keep_date_col=False,
    date_parser=None,
    dayfirst=False,
    cache_dates=True,
    iterator=False,
    chunksize=None,
    compression: 'CompressionOptions' = 'infer',
    thousands=None,
    decimal: 'str' = '.',
    lineterminator=None,
    quotechar='"',
    quoting=0,
    doublequote=True,
    escapechar=None,
    comment=None,
    encoding=None,
    encoding_errors: 'str | None' = 'strict',
    dialect=None,
    error_bad_lines=None,
    warn_bad_lines=None,
    on_bad_lines=None,
    delim_whitespace=False,
    low_memory=True,
    memory_map=False,
    float_precision=None,
    storage_options: 'StorageOptions' = None,
)
Docstring:
Read a comma-separated values (csv) file into DataFrame.

Also supports optionally iterating or breaking of the file
into chunks.

Additional help can be found in the online docs for
`IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

Parameters
----------
filepath_or_buffer : str, path object or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
    expected. A local file could be: file://localhost/path/to/table.csv.

    If you want to pass in a path object, pandas accepts any ``os.PathLike``.

    By file-like object, we refer to objects with a ``read()`` method, such as
    a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
sep : str, default ','
    Delimiter to use. If sep is None, the C engine cannot automatically detect
    the separator, but the Python parsing engine can, meaning the latter will
    be used and automatically detect the separator by Python's builtin sniffer
    tool, ``csv.Sniffer``. In addition, separators longer than 1 character and
    different from ``'\s+'`` will be interpreted as regular expressions and
    will also force the use of the Python parsing engine. Note that regex
    delimiters are prone to ignoring quoted data. Regex example: ``'\r\t'``.
delimiter : str, default ``None``
    Alias for sep.
header : int, list of int, None, default 'infer'
    Row number(s) to use as the column names, and the start of the
    data.  Default behavior is to infer the column names: if no names
    are passed the behavior is identical to ``header=0`` and column
    names are inferred from the first line of the file, if column
    names are passed explicitly then the behavior is identical to
    ``header=None``. Explicitly pass ``header=0`` to be able to
    replace existing names. The header can be a list of integers that
    specify row locations for a multi-index on the columns
    e.g. [0,1,3]. Intervening rows that are not specified will be
    skipped (e.g. 2 in this example is skipped). Note that this
    parameter ignores commented lines and empty lines if
    ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
    data rather than the first line of the file.
names : array-like, optional
    List of column names to use. If the file contains a header row,
    then you should explicitly pass ``header=0`` to override the column names.
    Duplicates in this list are not allowed.
index_col : int, str, sequence of int / str, or False, optional, default ``None``
  Column(s) to use as the row labels of the ``DataFrame``, either given as
  string name or column index. If a sequence of int / str is given, a
  MultiIndex is used.

  Note: ``index_col=False`` can be used to force pandas to *not* use the first
  column as the index, e.g. when you have a malformed file with delimiters at
  the end of each line.
usecols : list-like or callable, optional
    Return a subset of the columns. If list-like, all elements must either
    be positional (i.e. integer indices into the document columns) or strings
    that correspond to column names provided either by the user in `names` or
    inferred from the document header row(s). If ``names`` are given, the document
    header row(s) are not taken into account. For example, a valid list-like
    `usecols` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
    Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
    To instantiate a DataFrame from ``data`` with element order preserved use
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]`` for columns
    in ``['foo', 'bar']`` order or
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
    for ``['bar', 'foo']`` order.

    If callable, the callable function will be evaluated against the column
    names, returning names where the callable function evaluates to True. An
    example of a valid callable argument would be ``lambda x: x.upper() in
    ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
    parsing time and lower memory usage.
squeeze : bool, default False
    If the parsed data only contains one column then return a Series.

    .. deprecated:: 1.4.0
        Append ``.squeeze("columns")`` to the call to ``read_csv`` to squeeze
        the data.
prefix : str, optional
    Prefix to add to column numbers when no header, e.g. 'X' for X0, X1, ...

    .. deprecated:: 1.4.0
       Use a list comprehension on the DataFrame's columns after calling ``read_csv``.
mangle_dupe_cols : bool, default True
    Duplicate columns will be specified as 'X', 'X.1', ...'X.N', rather than
    'X'...'X'. Passing in False will cause data to be overwritten if there
    are duplicate names in the columns.
dtype : Type name or dict of column -> type, optional
    Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32,
    'c': 'Int64'}
    Use `str` or `object` together with suitable `na_values` settings
    to preserve and not interpret dtype.
    If converters are specified, they will be applied INSTEAD
    of dtype conversion.
engine : {'c', 'python', 'pyarrow'}, optional
    Parser engine to use. The C and pyarrow engines are faster, while the python engine
    is currently more feature-complete. Multithreading is currently only supported by
    the pyarrow engine.

    .. versionadded:: 1.4.0

        The "pyarrow" engine was added as an *experimental* engine, and some features
        are unsupported, or may not work correctly, with this engine.
converters : dict, optional
    Dict of functions for converting values in certain columns. Keys can either
    be integers or column labels.
true_values : list, optional
    Values to consider as True.
false_values : list, optional
    Values to consider as False.
skipinitialspace : bool, default False
    Skip spaces after delimiter.
skiprows : list-like, int or callable, optional
    Line numbers to skip (0-indexed) or number of lines to skip (int)
    at the start of the file.

    If callable, the callable function will be evaluated against the row
    indices, returning True if the row should be skipped and False otherwise.
    An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
skipfooter : int, default 0
    Number of lines at bottom of file to skip (Unsupported with engine='c').
nrows : int, optional
    Number of rows of file to read. Useful for reading pieces of large files.
na_values : scalar, str, list-like, or dict, optional
    Additional strings to recognize as NA/NaN. If dict passed, specific
    per-column NA values.  By default the following values are interpreted as
    NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
    '1.#IND', '1.#QNAN', '<NA>', 'N/A', 'NA', 'NULL', 'NaN', 'n/a',
    'nan', 'null'.
keep_default_na : bool, default True
    Whether or not to include the default NaN values when parsing the data.
    Depending on whether `na_values` is passed in, the behavior is as follows:

    * If `keep_default_na` is True, and `na_values` are specified, `na_values`
      is appended to the default NaN values used for parsing.
    * If `keep_default_na` is True, and `na_values` are not specified, only
      the default NaN values are used for parsing.
    * If `keep_default_na` is False, and `na_values` are specified, only
      the NaN values specified `na_values` are used for parsing.
    * If `keep_default_na` is False, and `na_values` are not specified, no
      strings will be parsed as NaN.

    Note that if `na_filter` is passed in as False, the `keep_default_na` and
    `na_values` parameters will be ignored.
na_filter : bool, default True
    Detect missing value markers (empty strings and the value of na_values). In
    data without any NAs, passing na_filter=False can improve the performance
    of reading a large file.
verbose : bool, default False
    Indicate number of NA values placed in non-numeric columns.
skip_blank_lines : bool, default True
    If True, skip over blank lines rather than interpreting as NaN values.
parse_dates : bool or list of int or names or list of lists or dict, default False
    The behavior is as follows:

    * boolean. If True -> try parsing the index.
    * list of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
      each as a separate date column.
    * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
      a single date column.
    * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call
      result 'foo'

    If a column or index cannot be represented as an array of datetimes,
    say because of an unparsable value or a mixture of timezones, the column
    or index will be returned unaltered as an object data type. For
    non-standard datetime parsing, use ``pd.to_datetime`` after
    ``pd.read_csv``. To parse an index or column with a mixture of timezones,
    specify ``date_parser`` to be a partially-applied
    :func:`pandas.to_datetime` with ``utc=True``. See
    :ref:`io.csv.mixed_timezones` for more.

    Note: A fast-path exists for iso8601-formatted dates.
infer_datetime_format : bool, default False
    If True and `parse_dates` is enabled, pandas will attempt to infer the
    format of the datetime strings in the columns, and if it can be inferred,
    switch to a faster method of parsing them. In some cases this can increase
    the parsing speed by 5-10x.
keep_date_col : bool, default False
    If True and `parse_dates` specifies combining multiple columns then
    keep the original columns.
date_parser : function, optional
    Function to use for converting a sequence of string columns to an array of
    datetime instances. The default uses ``dateutil.parser.parser`` to do the
    conversion. Pandas will try to call `date_parser` in three different ways,
    advancing to the next if an exception occurs: 1) Pass one or more arrays
    (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
    string values from the columns defined by `parse_dates` into a single array
    and pass that; and 3) call `date_parser` once for each row using one or
    more strings (corresponding to the columns defined by `parse_dates`) as
    arguments.
dayfirst : bool, default False
    DD/MM format dates, international and European format.
cache_dates : bool, default True
    If True, use a cache of unique, converted dates to apply the datetime
    conversion. May produce significant speed-up when parsing duplicate
    date strings, especially ones with timezone offsets.

    .. versionadded:: 0.25.0
iterator : bool, default False
    Return TextFileReader object for iteration or getting chunks with
    ``get_chunk()``.

    .. versionchanged:: 1.2

       ``TextFileReader`` is a context manager.
chunksize : int, optional
    Return TextFileReader object for iteration.
    See the `IO Tools docs
    <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
    for more information on ``iterator`` and ``chunksize``.

    .. versionchanged:: 1.2

       ``TextFileReader`` is a context manager.
compression : str or dict, default 'infer'
    For on-the-fly decompression of on-disk data. If 'infer' and '%s' is
    path-like, then detect compression from the following extensions: '.gz',
    '.bz2', '.zip', '.xz', or '.zst' (otherwise no compression). If using
    'zip', the ZIP file must contain only one data file to be read in. Set to
    ``None`` for no decompression. Can also be a dict with key ``'method'`` set
    to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``} and other
    key-value pairs are forwarded to ``zipfile.ZipFile``, ``gzip.GzipFile``,
    ``bz2.BZ2File``, or ``zstandard.ZstdDecompressor``, respectively. As an
    example, the following could be passed for Zstandard decompression using a
    custom compression dictionary:
    ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    .. versionchanged:: 1.4.0 Zstandard support.

thousands : str, optional
    Thousands separator.
decimal : str, default '.'
    Character to recognize as decimal point (e.g. use ',' for European data).
lineterminator : str (length 1), optional
    Character to break file into lines. Only valid with C parser.
quotechar : str (length 1), optional
    The character used to denote the start and end of a quoted item. Quoted
    items can include the delimiter and it will be ignored.
quoting : int or csv.QUOTE_* instance, default 0
    Control field quoting behavior per ``csv.QUOTE_*`` constants. Use one of
    QUOTE_MINIMAL (0), QUOTE_ALL (1), QUOTE_NONNUMERIC (2) or QUOTE_NONE (3).
doublequote : bool, default ``True``
   When quotechar is specified and quoting is not ``QUOTE_NONE``, indicate
   whether or not to interpret two consecutive quotechar elements INSIDE a
   field as a single ``quotechar`` element.
escapechar : str (length 1), optional
    One-character string used to escape other characters.
comment : str, optional
    Indicates remainder of line should not be parsed. If found at the beginning
    of a line, the line will be ignored altogether. This parameter must be a
    single character. Like empty lines (as long as ``skip_blank_lines=True``),
    fully commented lines are ignored by the parameter `header` but not by
    `skiprows`. For example, if ``comment='#'``, parsing
    ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in 'a,b,c' being
    treated as the header.
encoding : str, optional
    Encoding to use for UTF when reading/writing (ex. 'utf-8'). `List of Python
    standard encodings
    <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    .. versionchanged:: 1.2

       When ``encoding`` is ``None``, ``errors="replace"`` is passed to
       ``open()``. Otherwise, ``errors="strict"`` is passed to ``open()``.
       This behavior was previously only the case for ``engine="python"``.

    .. versionchanged:: 1.3.0

       ``encoding_errors`` is a new argument. ``encoding`` has no longer an
       influence on how encoding errors are handled.

encoding_errors : str, optional, default "strict"
    How encoding errors are treated. `List of possible values
    <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    .. versionadded:: 1.3.0

dialect : str or csv.Dialect, optional
    If provided, this parameter will override values (default or not) for the
    following parameters: `delimiter`, `doublequote`, `escapechar`,
    `skipinitialspace`, `quotechar`, and `quoting`. If it is necessary to
    override values, a ParserWarning will be issued. See csv.Dialect
    documentation for more details.
error_bad_lines : bool, optional, default ``None``
    Lines with too many fields (e.g. a csv line with too many commas) will by
    default cause an exception to be raised, and no DataFrame will be returned.
    If False, then these "bad lines" will be dropped from the DataFrame that is
    returned.

    .. deprecated:: 1.3.0
       The ``on_bad_lines`` parameter should be used instead to specify behavior upon
       encountering a bad line instead.
warn_bad_lines : bool, optional, default ``None``
    If error_bad_lines is False, and warn_bad_lines is True, a warning for each
    "bad line" will be output.

    .. deprecated:: 1.3.0
       The ``on_bad_lines`` parameter should be used instead to specify behavior upon
       encountering a bad line instead.
on_bad_lines : {'error', 'warn', 'skip'} or callable, default 'error'
    Specifies what to do upon encountering a bad line (a line with too many fields).
    Allowed values are :

        - 'error', raise an Exception when a bad line is encountered.
        - 'warn', raise a warning when a bad line is encountered and skip that line.
        - 'skip', skip bad lines without raising or warning when they are encountered.

    .. versionadded:: 1.3.0

        - callable, function with signature
          ``(bad_line: list[str]) -> list[str] | None`` that will process a single
          bad line. ``bad_line`` is a list of strings split by the ``sep``.
          If the function returns ``None``, the bad line will be ignored.
          If the function returns a new list of strings with more elements than
          expected, a ``ParserWarning`` will be emitted while dropping extra elements.
          Only supported when ``engine="python"``

    .. versionadded:: 1.4.0

delim_whitespace : bool, default False
    Specifies whether or not whitespace (e.g. ``' '`` or ``'    '``) will be
    used as the sep. Equivalent to setting ``sep='\s+'``. If this option
    is set to True, nothing should be passed in for the ``delimiter``
    parameter.
low_memory : bool, default True
    Internally process the file in chunks, resulting in lower memory use
    while parsing, but possibly mixed type inference.  To ensure no mixed
    types either set False, or specify the type with the `dtype` parameter.
    Note that the entire file is read into a single DataFrame regardless,
    use the `chunksize` or `iterator` parameter to return the data in chunks.
    (Only valid with C parser).
memory_map : bool, default False
    If a filepath is provided for `filepath_or_buffer`, map the file object
    directly onto memory and access the data directly from there. Using this
    option can improve performance because there is no longer any I/O overhead.
float_precision : str, optional
    Specifies which converter the C engine should use for floating-point
    values. The options are ``None`` or 'high' for the ordinary converter,
    'legacy' for the original lower precision pandas converter, and
    'round_trip' for the round-trip converter.

    .. versionchanged:: 1.2

storage_options : dict, optional
    Extra options that make sense for a particular storage connection, e.g.
    host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
    are forwarded to ``urllib`` as header options. For other URLs (e.g.
    starting with "s3://", and "gcs://") the key-value pairs are forwarded to
    ``fsspec``. Please see ``fsspec`` and ``urllib`` for more details.

    .. versionadded:: 1.2

Returns
-------
DataFrame or TextParser
    A comma-separated values (csv) file is returned as two-dimensional
    data structure with labeled axes.

See Also
--------
DataFrame.to_csv : Write DataFrame to a comma-separated values (csv) file.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_fwf : Read a table of fixed-width formatted lines into DataFrame.

Examples
--------

In [3]:
prisonData = pd.read_csv('data/facilities.csv')  #We are passing just the filepath here

Quick question. What is the datatype for prisonData.

If you want to just see the first few records or last few records you can use the methods head and tail respectively

In [4]:
prisonData.head()

,nyt_id,facility_name,facility_type,facility_city,facility_county,facility_county_fips,facility_state,facility_lng,facility_lat,latest_inmate_population,max_inmate_population_2020,total_inmate_cases,total_inmate_deaths,total_officer_cases,total_officer_deaths,note
0,F3EFE858,Alex City Work Release prison,Low-security work release,Alex City,Coosa,1037,Alabama,-86.009015,32.904507,188.0,NaN,77,0,17,0.0,NaN
1,5B910220,Alabama Therapeutic Education Facility prison,State rehabilitation center,Columbiana,Shelby,1117,Alabama,-86.624067,33.180755,272.0,NaN,11,1,2,0.0,NaN
2,02FB1675,Bibb Correctional Facility,State prison,Brent,Bibb,1007,Alabama,-87.162781,32.920754,1725.0,1825.0,164,3,61,0.0,NaN
3,6378F6C4,Birmingham Women's Community Based Facility an...,State prison,Birmingham,Jefferson,1073,Alabama,-86.808344,33.531101,192.0,NaN,17,0,28,0.0,NaN
4,EAABF900,Bullock Correctional Facility,State prison,Bessemer,Bullock,1011,Alabama,-85.673927,32.147144,1477.0,1577.0,162,5,80,1.0,NaN

In [5]:
prisonData.tail()

,nyt_id,facility_name,facility_type,facility_city,facility_county,facility_county_fips,facility_state,facility_lng,facility_lat,latest_inmate_population,max_inmate_population_2020,total_inmate_cases,total_inmate_deaths,total_officer_cases,total_officer_deaths,note
2634,15289545,North Lake federal prison,Federal prison,Baldwin,Lake,26085,Michigan,-85.839287,43.928551,1614.0,1614.0,125,2,0,0.0,NaN
2635,1558C2BF,Rivers federal prison,Federal prison,Winton,Hertford,37091,North Carolina,-76.958751,36.403668,6.0,1255.0,68,1,0,0.0,NaN
2636,C9CF62B9,Reeves County federal prison,Federal prison,Pecos,Reeves,48389,Texas,-103.493817,31.423563,1005.0,NaN,46,1,0,0.0,NaN
2637,364869B9,Flightline federal prison,Federal prison,Big Spring,Howard,48227,Texas,-101.521236,32.224310,1652.0,NaN,34,1,0,0.0,NaN
2638,5CFB7978,Moshannon Valley federal prison,Federal prison,Philipsburg,Clearfield,42033,Pennsylvania,-78.242177,40.921117,94.0,1774.0,197,4,0,0.0,NaN

How many rows and columns are there in our prison dataset

Can you enumerate the columns and the index in this dataset

What are the datatypes for each columns

Can you select the columns 'total_inmate_cases' from the dataset. What is the datatype for the column?

Can you select the columns 'nyt_id', 'facility_name','facility_state','latest_inmate_population' and 'total_inmate_cases' from the dataset

Some basic descriptive stats for the dataset

In [6]:
prisonData.describe()

,facility_county_fips,facility_lng,facility_lat,latest_inmate_population,max_inmate_population_2020,total_inmate_cases,total_inmate_deaths,total_officer_cases,total_officer_deaths
count,2639.000000,2639.000000,2639.000000,1593.000000,838.000000,2639.000000,2639.000000,2639.000000,2638.000000
mean,29186.422887,-91.193161,37.280626,822.386692,1269.529833,199.431603,0.983327,42.561955,0.083776
std,15809.439620,14.836097,5.437975,862.009973,936.057182,420.344387,2.982973,89.408213,0.363528
min,1003.000000,-165.412569,18.423135,1.000000,27.000000,0.000000,0.000000,0.000000,0.000000
25%,13233.000000,-97.649683,33.422542,163.000000,602.500000,8.000000,0.000000,0.000000,0.000000
50%,30017.000000,-86.812013,37.606861,579.000000,1066.500000,59.000000,0.000000,9.000000,0.000000
75%,42033.000000,-81.115561,40.933270,1197.000000,1681.000000,226.500000,0.000000,50.500000,0.000000
max,72061.000000,-66.112209,64.833337,8616.000000,6150.000000,12290.000000,45.000000,1718.000000,6.000000

While running descriptive stats on some of the columns such as facility_county_fips doesn't make any sense, it can easily provide an overview for columns such as total_inmate_cases (mean = 199.431603,max = 12290.000000).

Can you just print the descriptive statistics for total_inmate_cases and total_inmate_deaths

## Some basic calculations

Create a new field cases_per_population which is calculated as total_inmate_cases/latest_inmate_population

Create a new field deaths_per_population which is calculated as total_inmate_deaths/latest_inmate_population

Find the correctional facility with the maximum number of inmate cases?

Find the correctional facility with the maximum number of inmate deaths?

## Selections

 Can you select the first 10 rows of this dataset.

Can you select the last 100 rows for the total_inmate_cases.

Can you select the last 100 rows for the total_inmate_cases and total_inmate_deaths.

Can you select the last 100 rows for the total_inmate_cases and calculate the mean.

## Filtering and updating data

Let us find all facilities with more than 1000 inmate cases

In [7]:
prisonData[prisonData.total_inmate_cases>1000]

,nyt_id,facility_name,facility_type,facility_city,facility_county,facility_county_fips,facility_state,facility_lng,facility_lat,latest_inmate_population,max_inmate_population_2020,total_inmate_cases,total_inmate_deaths,total_officer_cases,total_officer_deaths,note
34,7120943C,Goose Creek Correctional Center,State prison,Wasilla,Matanuska-Susitna,2170,Alaska,-149.990022,61.360095,1293.0,1348.0,1041,0,0,0.0,NaN
50,AA807759,Arizona State Prison Complex – Douglas,State prison,Douglas,Cochise,4003,Arizona,-109.600147,31.445500,1848.0,2132.0,1163,0,0,0.0,NaN
51,91B22ADD,Eyman Complex prison,State prison,Florence,Pinal,4021,Arizona,-111.337569,33.031474,5362.0,5471.0,2023,5,0,0.0,NaN
52,0CF96DB1,Arizona State Prison Complex – Yuma,State prison,San Luis,Yuma,4027,Arizona,-114.643082,32.494131,4316.0,4862.0,2010,6,0,0.0,NaN
58,E830C278,Arizona State Prison Complex – Lewis,State prison,Buckeye,Maricopa,4013,Arizona,-112.644365,33.201281,4617.0,4617.0,1310,2,0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2568,233CC887,Pollock federal prison complex,Federal prison,Pollock,Grant,22043,Louisiana,-92.432853,31.465159,2590.0,2754.0,1211,0,0,0.0,NaN
2588,79BEB932,Seagoville federal prison,Federal prison,Seagoville,Dallas,48113,Texas,-96.567986,32.655933,1798.0,2004.0,1336,5,0,0.0,NaN
2599,4A388A9A,Terre Haute federal prison complex,Federal prison,Terre Haute,Vigo,18167,Indiana,-87.455019,39.410206,2291.0,2624.0,1248,6,0,0.0,NaN
2608,D9A37098,Tucson federal prison complex,Federal prison,Tucson,Pima,4019,Arizona,-110.865276,32.084730,1586.0,1931.0,1067,10,0,0.0,NaN
2609,20C2E350,Victorville federal prison complex,Federal prison,Victorville,San Bernardino,6071,California,-117.364873,34.567075,3310.0,4210.0,1696,3,0,0.0,NaN

Now can you try to create a subset of our dataset containing only facilities from Ohio?

Can you try to find out facilties in Franklin County, Ohio with more than 30 inmate cases.

Which is the facility in Ohio with most number of inamte deaths

## Dealing with missing data

Data gaps are common in real-world datasets. Let us see the records with missing latest_inmate_population.

In [8]:
prisonData[prisonData['latest_inmate_population'].isna()]

,nyt_id,facility_name,facility_type,facility_city,facility_county,facility_county_fips,facility_state,facility_lng,facility_lat,latest_inmate_population,max_inmate_population_2020,total_inmate_cases,total_inmate_deaths,total_officer_cases,total_officer_deaths,note
39,ED29F8B4,Palmer Correctional Center,State prison,Palmer,Matanuska-Susitna,2170,Alaska,-149.007972,61.691417,NaN,NaN,0,0,0,0.0,NaN
57,07E5D203,Maricopa Reentry Center,State prison,Phoenix,Maricopa,4013,Arizona,-112.120433,33.707162,NaN,NaN,0,0,0,0.0,NaN
61,26CFE1E6,Pima Reentry Center,State prison,Tucson,Pima,4019,Arizona,-110.990714,32.204199,NaN,NaN,0,0,0,0.0,NaN
79,9AA13461,Northwest Arkansas Work Release prison,Low-security work release,Springdale,Washington,5143,Arkansas,-94.135712,36.174948,NaN,NaN,69,0,4,0.0,NaN
88,7C68181A,Arkansas Juvenile Assessment and Treatment Center,State juvenile detention,Alexander,Saline,5125,Arkansas,-92.494695,34.637731,NaN,NaN,63,0,67,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2620,786CB2A3,Roseville federal prison halfway house,Federal halfway house,Roseville,Ramsey,27123,Minnesota,-93.124231,44.994233,NaN,NaN,8,0,0,0.0,NaN
2622,175CAB9F,Watkinson House federal prison halfway house,Federal halfway house,Hartford,Hartford,9003,Connecticut,-72.689572,41.772700,NaN,NaN,1,0,0,0.0,NaN
2624,87DBAF80,Parsons House federal prison halfway house,Federal halfway house,Milwaukee,Milwaukee,55079,Wisconsin,-87.960541,43.039124,NaN,NaN,1,0,0,0.0,NaN
2625,E3A87C51,Flagstaff federal prison halfway house,Federal halfway house,Flagstaff,Coconino,4005,Arizona,-111.640458,35.187256,NaN,NaN,1,0,0,0.0,NaN
2626,A7B2A8A7,Garden Grove federal prison halfway house,Federal halfway house,Garden Grove,Orange,6059,California,-117.936021,33.775822,NaN,NaN,11,0,0,0.0,NaN

Wowwww that's a lot of records.

Now can you filter out the records that doesnot have a null value for latest_inmate_population

## Data types

Let us see the datatype for the column facility_county_fips

In [9]:
prisonData['facility_county_fips'].dtype

dtype('int64')

Can you convert this column to string?

## Finding Unique Values

We can use unique() method to extract out unique values from a column. For example let's extract out the unique values from facility_state column.

In [10]:
prisonData['facility_state'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia',
       'Hawaii', 'Idaho', 'Texas', 'Illinois', 'Indiana', 'Iowa',
       'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia',
       'Wisconsin', 'Wyoming', 'District of Columbia', 'kentucky', nan,
       'Puerto Rico'], dtype=object)

## Sorting data

DataFrames/Series can be sorted using sort_values() method. Let us sort our dataset using total_inmate_cases in descending order.

In [11]:
prisonData.sort_values(by='total_inmate_cases',ascending=False)

,nyt_id,facility_name,facility_type,facility_city,facility_county,facility_county_fips,facility_state,facility_lng,facility_lat,latest_inmate_population,max_inmate_population_2020,total_inmate_cases,total_inmate_deaths,total_officer_cases,total_officer_deaths,note
2247,E5DA4853,U.S. Marshalls,U.S. Marshalls,NaN,Muskogee,40101,NaN,-95.374390,35.749979,NaN,NaN,12290,31,0,0.0,NaN
1458,046ADCE7,Fresno County jail,Jail,Fresno,Fresno,6019,California,-119.789751,36.738211,2042.0,NaN,3814,0,171,1.0,NaN
92,41367DB9,Avenal State Prison,State prison,Avenal,Kings,6031,California,-120.123310,35.974332,3469.0,4158.0,3108,8,532,0.0,NaN
120,19DE7187,Substance Abuse Treatment Facility and State P...,State prison,Corcoran,Kings,6031,California,-119.554854,36.058048,4488.0,4531.0,3011,7,636,0.0,NaN
106,550543A1,Soledad prison,State prison,Soledad,Monterey,6053,California,-121.382640,36.470807,4374.0,NaN,2719,18,355,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2374,0A1D2EB9,Carver County Jail,Detention center,Chaska,Carver,27019,Minnesota,-93.592635,44.787408,NaN,NaN,0,0,0,0.0,NaN
1924,C75A68C0,Vance County Detention Center,Jail,Henderson,Vance,37181,North Carolina,-78.407240,36.330646,NaN,NaN,0,0,3,0.0,NaN
2372,3867C0A8,Sheridan federal prison,Detention center,Sheridan,Yamhill,41071,Washington,-123.381623,45.084014,NaN,NaN,0,0,0,0.0,NaN
344,5E4670FA,Melbourne Center for Personal Growth youth center,State juvenile detention,Melbourne,Brevard,12009,Florida,-80.713169,28.122853,12.0,NaN,0,0,6,0.0,NaN
693,64DD6F6E,Flowood Community Work Center/Restitution Center,State prison,Flowood,Hinds,28049,Mississippi,-90.193159,32.296677,NaN,NaN,0,0,0,0.0,NaN

As you can see the U.S. Marshalls facility has the highest number of total_inmate_cases followed by Fresno County jail.

Can you sort the dataset using total_inmate_deaths in descending order.

## Writing data to a file

We can use the to_csv() method to write a DataFrame to a CSV file. Let's write a subset of our file containing all the facilities with 1,000 or more inmate cases to a file called facilities_1000ormore.csv to the data folder.

In [12]:
#let's create the subset
prisonData1000OrMore = prisonData[prisonData['total_inmate_cases']>=1000]
prisonData1000OrMore

,nyt_id,facility_name,facility_type,facility_city,facility_county,facility_county_fips,facility_state,facility_lng,facility_lat,latest_inmate_population,max_inmate_population_2020,total_inmate_cases,total_inmate_deaths,total_officer_cases,total_officer_deaths,note
34,7120943C,Goose Creek Correctional Center,State prison,Wasilla,Matanuska-Susitna,2170,Alaska,-149.990022,61.360095,1293.0,1348.0,1041,0,0,0.0,NaN
50,AA807759,Arizona State Prison Complex – Douglas,State prison,Douglas,Cochise,4003,Arizona,-109.600147,31.445500,1848.0,2132.0,1163,0,0,0.0,NaN
51,91B22ADD,Eyman Complex prison,State prison,Florence,Pinal,4021,Arizona,-111.337569,33.031474,5362.0,5471.0,2023,5,0,0.0,NaN
52,0CF96DB1,Arizona State Prison Complex – Yuma,State prison,San Luis,Yuma,4027,Arizona,-114.643082,32.494131,4316.0,4862.0,2010,6,0,0.0,NaN
58,E830C278,Arizona State Prison Complex – Lewis,State prison,Buckeye,Maricopa,4013,Arizona,-112.644365,33.201281,4617.0,4617.0,1310,2,0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2568,233CC887,Pollock federal prison complex,Federal prison,Pollock,Grant,22043,Louisiana,-92.432853,31.465159,2590.0,2754.0,1211,0,0,0.0,NaN
2588,79BEB932,Seagoville federal prison,Federal prison,Seagoville,Dallas,48113,Texas,-96.567986,32.655933,1798.0,2004.0,1336,5,0,0.0,NaN
2599,4A388A9A,Terre Haute federal prison complex,Federal prison,Terre Haute,Vigo,18167,Indiana,-87.455019,39.410206,2291.0,2624.0,1248,6,0,0.0,NaN
2608,D9A37098,Tucson federal prison complex,Federal prison,Tucson,Pima,4019,Arizona,-110.865276,32.084730,1586.0,1931.0,1067,10,0,0.0,NaN
2609,20C2E350,Victorville federal prison complex,Federal prison,Victorville,San Bernardino,6071,California,-117.364873,34.567075,3310.0,4210.0,1696,3,0,0.0,NaN

In [13]:
prisonData1000OrMore.to_csv(r'data/facilities_1000ormore.csv',index=False)

In the next chapter we will look into advanced Pandas concepts such as Grouping and Joining.